version : "3"
services:
  voting:
    image: voting-app
    ports:
      - "3001:80"
    depends_on:
      - redis
  result:
    image: result-app
    ports:
      - "3002:80"
    depends_on:
      - db
  worker:
    image: worker-app
    depends_on:
      - redis
      - db
  redis:
    image: redis
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust