services:
  vote:
    build: ./vote
    ports:
      - "5001:80"
    depends_on:
      - redis
  result:
    build: ./result
    ports:
      - "5002:80"
    depends_on:
      - db
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
  redis:
    image: redis
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust